displayName=Info Toggles
author=CreeperCat1
description=Moves multiple tooltips into an info toggle.
tags=spell, info, magic, mobile, spellbook, tooltip, prayer, toggle
version=
plugins=com.infotoggles.InfoTogglesPlugin
build=standard