displayName=Spell Info
author=CreeperCat1
description=Moves spell tooltip into an info toggle.
tags=spell, info, magic, mobile, spellbook, tooltip
version=
plugins=com.spell_info.Spell_InfoPlugin
build=standard